# inventory.ini
[machine]
fedora1 ansible_host=127.0.0.1 ansible_port=2221

[test_machine]
fedora2 ansible_host=127.0.0.1 ansible_port=2222
fedora3 ansible_host=127.0.0.1 ansible_port=2223

[machine:vars]
ansible_user=ci
ansible_python_interpreter=/usr/bin/python3
test_machines_target_machines_group_name="machine"
test_machines_group_name="test_machine"
test_machines_env_variable_prefix="CLUSTERING_BAREMETAL_HOST"
test_machines_file_path="/tmp/test-machines.txt"
# Password based authentication
#ansible_password=ci
#ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PubkeyAuthentication=no'
# SSH Pivate Key based authentication
ansible_ssh_private_key_file=./.ssh/ci_test
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes'

[test_machine:vars]
ansible_user=ci
ansible_python_interpreter=/usr/bin/python3
# Password based authentication
#ansible_password=ci
#ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PubkeyAuthentication=no'
# SSH Pivate Key based authentication
ansible_ssh_private_key_file=./.ssh/ci_test
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes'
