# inventory.ini
[machine]
fedora1 ansible_host=127.0.0.1 ansible_port=2221

[test-machine]
fedora2 ansible_host=127.0.0.1 ansible_port=2222
fedora3 ansible_host=127.0.0.1 ansible_port=2223

[machine:vars]
ansible_user=ansible
#ansible_password=ansible
#ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PubkeyAuthentication=no'
ansible_ssh_private_key_file=./.ssh/ansible_test
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes'
ansible_python_interpreter=/usr/bin/python3
test_machines_target_machines_group_name="machine"
test_machines_group_name="test-machine"
test_machines_env_variable_prefix="CLUSTERING_BAREMETAL_HOST"
test_machines_file_path="/tmp/test-machines.txt"

[test-machine:vars]
ansible_user=ansible
#ansible_password=ansible
#ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PubkeyAuthentication=no'
ansible_ssh_private_key_file=./.ssh/ansible_test
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes'
ansible_python_interpreter=/usr/bin/python3
