---
- name: Test
  hosts: all
  gather_facts: yes
  tasks:
    # - name: Gather all host IP addresses
    #   set_fact:
    #     all_host_ips: "{{ groups['all'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list }}"
    #   run_once: true
    #   delegate_to: localhost
    #   delegate_facts: true

    # - name: Print all available facts
    #   ansible.builtin.debug:
    #     var: ansible_facts['all_ipv4_addresses']
    
    - name: Fetch IP address using Python
      #delegate_to: localhost
      shell: "{{ ansible_playbook_python }} -c 'import socket; print(socket.gethostbyname(socket.gethostname()))'"
      register: ip_address_result

    - name: Display the IP address
      debug:
        var: ip_address_result.stdout

    # - name: Create file with all IPs
    #   when: inventory_hostname in groups["machine"]
    #   copy:
    #     content: |
    #       {% for host in groups['test_machine'] %}
    #       CLUSTERING_BAREMETAL_HOST{{ loop.index }}={{ hostvars[host]['ansible_default_ipv4']['address'] }}
    #       {% endfor %}
    #     dest: /tmp/all_hosts_ips.txt
    #     mode: '0644'

    # - name: Create templated file with all IPs
    #   when: inventory_hostname in groups["machine"]
    #   template:
    #     src: templates/test-machines.txt.j2
    #     dest: /tmp/test-machines.txt

#- name: Generate SSH key pair on coordinator node
#  hosts: machine
#  become: yes
#  roles:
#    - role: ssh_keygen
#      vars:
#        ssh_key_user: ci
#        test_machines_group_name: "test_machine"
#
#- name: Distribute public key to worker nodes
#  hosts: test_machine
#  become: yes
#  roles:
#    - role: ssh_authorize
#      vars:
#        ssh_key_user: ci
#        ssh_key_group: ci
#        ssh_public_key: "{{ hostvars[groups['machine'][0]]['ssh_public_key'] }}"
#
#- name: Create file with all host IPs on each coordinator node
#  hosts: machine
#  gather_facts: yes
#  roles:
#    - role: create_test_machines_file
#      vars:
#        test_machines_file_path: "/home/ci/test-machines.txt"
#        test_machines_file_owner: "ci"
#        test_machines_file_group: "ci"

- name: Configure SSH Cluster
  hosts: machine:test_machine
  gather_facts: yes
  roles:
    - role: ssh_cluster
      vars:
        controller_nodes_group_name: "machine"
        worker_nodes_group_name: "test_machine"
        ssh_key_user: "ci"