---
ssh_key_user: ci
ssh_key_group: "{{ ssh_key_user }}"
ssh_key_id: "_internal"
ssh_key_type: ed25519
ssh_key_file: ".ssh/id{{ ssh_key_id }}_{{ ssh_key_type }}"
ssh_key_comment: "{{ ssh_key_user }}@{{ inventory_hostname }}"
test_machines_group_name: "test_machine"
